import { createBrowserSupabase } from '@/lib/supabase';

// ─── Timeout helper ───────────────────────────────────────────────
function withTimeout<T>(thenable: PromiseLike<T>, ms: number): Promise<T> {
  return Promise.race([
    Promise.resolve(thenable),
    new Promise<T>((_, reject) =>
      setTimeout(() => reject(new Error('TIMEOUT')), ms)
    ),
  ]);
}

export interface ClaimDocument {
  id: string;
  name: string;
  original_name: string;
  file_path: string;
  file_size: number | null;
  mime_type: string | null;
  type: string;
  claim_id: string;
  uploaded_by: string;
  created_at: string;
}

/**
 * Upload a file to Supabase Storage and create a document record.
 */
export async function uploadClaimDocument(
  claimId: string,
  file: File,
  docType: 'invoice' | 'claim' | 'approval' | 'completion_certificate' | 'other',
  uploadedBy: string,
): Promise<ClaimDocument> {
  const supabase = createBrowserSupabase();

  // Generate unique storage path
  const timestamp = Date.now();
  const safeName = file.name.replace(/[^a-zA-Z0-9._\u0600-\u06FF-]/g, '_');
  const storagePath = `claims/${claimId}/${timestamp}_${safeName}`;

  // Upload to Supabase Storage
  const { error: uploadErr } = await supabase.storage
    .from('documents')
    .upload(storagePath, file, {
      cacheControl: '3600',
      upsert: false,
    });

  if (uploadErr) throw uploadErr;

  // Insert document record
  const { data, error: insertErr } = await supabase
    .from('documents')
    .insert({
      name: file.name,
      original_name: file.name,
      file_path: storagePath,
      file_size: file.size,
      mime_type: file.type,
      type: docType,
      claim_id: claimId,
      uploaded_by: uploadedBy,
    })
    .select()
    .single();

  if (insertErr) throw insertErr;
  return data;
}

/**
 * Fetch documents for a claim.
 */
export async function fetchClaimDocuments(claimId: string): Promise<ClaimDocument[]> {
  const supabase = createBrowserSupabase();
  const query = supabase
    .from('documents')
    .select('*')
    .eq('claim_id', claimId)
    .order('created_at');

  const { data, error } = await withTimeout(
    query as unknown as Promise<{ data: ClaimDocument[] | null; error: unknown }>,
    8000
  );

  if (error) throw error;
  return data || [];
}

/**
 * Generate a short-lived signed download URL for a stored document.
 * Falls back to an empty string if the storage operation fails.
 *
 * @deprecated Use secureDocumentDownload() for all new code.
 *             This client-side method is unreliable due to storage RLS.
 */
export async function getDocumentDownloadUrl(filePath: string): Promise<string> {
  const supabase = createBrowserSupabase();
  const { data, error } = await supabase.storage
    .from('documents')
    .createSignedUrl(filePath, 3600); // 1-hour expiry
  if (error || !data?.signedUrl) return '';
  return data.signedUrl;
}

/**
 * Download result from the secure server-side endpoint.
 */
export interface SecureDownloadResult {
  ok: boolean;
  url?: string;
  error?: string;
  code?: string;
}

/**
 * Securely download a document via the server-side authorization endpoint.
 *
 * This is the ONLY approved download path for CONVERA documents.
 * The server validates:
 *  - User authentication
 *  - Contract role access
 *  - Certificate access rules (contractor only after approval)
 *  - File existence in storage
 *
 * Returns a signed URL generated by the admin client (bypasses storage RLS).
 */
export async function secureDocumentDownload(documentId: string): Promise<SecureDownloadResult> {
  try {
    const supabase = createBrowserSupabase();
    const { data: { session } } = await supabase.auth.getSession();
    const token = session?.access_token;

    if (!token) {
      return { ok: false, error: 'يجب تسجيل الدخول أولاً', code: 'AUTH_REQUIRED' };
    }

    const res = await fetch(`/api/documents/${documentId}/download`, {
      method: 'GET',
      headers: {
        Authorization: `Bearer ${token}`,
      },
    });

    const json = await res.json();

    if (!res.ok) {
      console.warn(`[secureDocumentDownload] Failed: docId=${documentId} status=${res.status} code=${json.code}`);
      return {
        ok: false,
        error: json.error || 'فشل في تحميل المستند',
        code: json.code,
      };
    }

    if (!json.url) {
      return { ok: false, error: 'لم يتم إنشاء رابط التنزيل', code: 'NO_URL' };
    }

    return { ok: true, url: json.url };
  } catch (e) {
    console.error('[secureDocumentDownload] Exception:', e);
    return {
      ok: false,
      error: (e instanceof Error ? e.message : 'خطأ في الاتصال'),
      code: 'NETWORK_ERROR',
    };
  }
}

/**
 * Trigger a browser file download from a secure document download result.
 * Returns true if download was triggered, false + error message if not.
 */
export async function downloadDocument(
  documentId: string,
  fileName: string,
): Promise<{ ok: boolean; error?: string; code?: string }> {
  const result = await secureDocumentDownload(documentId);

  if (!result.ok || !result.url) {
    return { ok: false, error: result.error, code: result.code };
  }

  // Trigger browser download
  const a = window.document.createElement('a');
  a.href = result.url;
  a.download = fileName;
  a.target = '_blank';
  a.rel = 'noopener noreferrer';
  a.click();

  return { ok: true };
}

/**
 * Check if a claim has the required approved invoice attached.
 */
export async function hasRequiredInvoice(claimId: string): Promise<boolean> {
  const supabase = createBrowserSupabase();
  const { count, error } = await supabase
    .from('documents')
    .select('id', { count: 'exact', head: true })
    .eq('claim_id', claimId)
    .eq('type', 'invoice');

  if (error) return false;
  return (count || 0) > 0;
}
